experiment_name: 'customed_v2'
output_dir: 'outputs'
eval: false
seed: 42

model:
  class_name: 'model.customed_v2.resnet50'
  params:
    num_classes: 1000
    pretrained: true
  
trainer:
  accelerator: "gpu"
  devices: [0, 1, 2, 3, 4]
  max_epochs: 30

checkpoint:
  path:

dataset:
  name: imagenet
  data_dir: './Dataset/imagenet'
  num_classes: 1000
  batch_size: 64
  workers: 10

optimizer:
  class_name: 'SGD'
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_name: 'StepLR'
  params:
    step_size: 10
    gamma: 0.1

quan:
