experiment_name: 'quan-resnet50-customed-imagenet'
output_dir: 'outputs'
eval: false
seed: 42

model:
  class_name: 'model.quan_customed.resnet50'
  params:
    num_classes: 1000
    pretrained: '/lamport/makkapakka/hzheng/neuralzipModified_v2/outputs/resnet50-imagenet/v1/checkpoints/epoch=94-val_loss_epoch=1.4398-val_acc_epoch=0.6522.ckpt'
  
trainer:
  accelerator: "gpu"
  devices: [0, 1, 2, 3, 4]
  max_epochs: 100

checkpoint:
  path:

dataset:
  name: imagenet
  data_dir: './Dataset/imagenet'
  num_classes: 1000
  batch_size: 64
  workers: 10

optimizer:
  class_name: 'SGD'
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_name: 'StepLR'
  params:
    step_size: 30
    gamma: 0.1

quan:
